version: '2'
services:
  relayer:
    container_name: hpl-relayer
    # image: gcr.io/abacus-labs-dev/hyperlane-agent:9736164-20240307-131918
    image:  gcr.io/abacus-labs-dev/hyperlane-agent:latest
    user: root
    # restart: always
    entrypoint: ['sh', '-c']
    environment:
      - RUST_LOG=info,hyperlane=debug,relayer=debug,hyperlane_cosmos=debug
      - HYP_BASE_TRACING_LEVEL=debug
    command:
      - |
        rm -rf /app/config/* && \
        cp "/etc/hyperlane/agent-config.docker.json" "/app/config/agent-config.json" && \
        CONFIG_FILES="/etc/hyperlane/relayer.json" \
          ./relayer --allowLocalCheckpointSyncers false --metrics 0.0.0.0:9090 --api 0.0.0.0:9090
    ports:
      - 9110:9090
    volumes:
      - ./hyperlane:/etc/hyperlane
      - ./relayer:/etc/data
      - ./validator:/etc/validator
      

  

  validator-terraclassic:
    container_name: hpl-validator-terraclassic
    # image: gcr.io/abacus-labs-dev/hyperlane-agent:9736164-20240307-131918
    image: gcr.io/abacus-labs-dev/hyperlane-agent:latest
    user: root
    # restart: always
    entrypoint: ['sh', '-c']
    command:
      - |
        rm -rf /app/config/* && \
        cp "/etc/hyperlane/agent-config.docker.json" "/app/config/agent-config.json" && \
        CONFIG_FILES="/etc/hyperlane/validator.terraclassic.json" \
          ./validator
    ports:
      - 9121:9090
    volumes:
      - ./hyperlane:/etc/hyperlane
      - ./validator:/etc/validator
      - ./validator/terraclassic:/etc/data
